import type { Manifest, Model, Provider } from '@rttnd/llm-shared'

export const testProviders: Provider[] = [
  {
    value: 'openai',
    name: 'OpenAI',
    keyPlaceholder: 'sk-...',
    website: 'https://platform.openai.com/api-keys',
    status: 'latest',
  },
  {
    value: 'anthropic',
    name: 'Anthropic',
    keyPlaceholder: 'sk-ant-...',
    website: 'https://console.anthropic.com/settings/keys',
    status: 'latest',
  },
  {
    value: 'google',
    name: 'Google',
    keyPlaceholder: 'AIza...',
    website: 'https://aistudio.google.com/apikey',
    status: 'latest',
  },
  {
    value: 'xai',
    name: 'xAI',
    keyPlaceholder: 'xai-...',
    website: 'https://console.x.ai/',
    status: 'latest',
  },
]

export const testModels: Model[] = [
  // OpenAI models
  {
    id: 'openai-gpt-5',
    value: 'gpt-5',
    provider: 'openai',
    name: 'GPT-5 (high)',
    alias: 'GPT-5',
    capabilities: { text: true, vision: true, reasoning: true, toolUse: true, json: true },
    iq: 5,
    speed: 3,
    metrics: { contextWindow: 128000, intelligenceIndex: 72 },
    releaseDate: '2025-05-15',
    status: 'latest',
  },
  {
    id: 'openai-gpt-5-mini',
    value: 'gpt-5-mini',
    provider: 'openai',
    name: 'GPT-5 mini',
    capabilities: { text: true, vision: true, toolUse: true, json: true },
    iq: 4,
    speed: 5,
    metrics: { contextWindow: 128000, intelligenceIndex: 58 },
    releaseDate: '2025-06-01',
    status: 'latest',
  },
  {
    id: 'openai-gpt-4o',
    value: 'gpt-4o',
    provider: 'openai',
    name: 'GPT-4o',
    capabilities: { text: true, vision: true, toolUse: true, json: true },
    iq: 4,
    speed: 4,
    metrics: { contextWindow: 128000, intelligenceIndex: 55 },
    releaseDate: '2024-05-13',
    status: 'all',
  },
  {
    id: 'openai-o3',
    value: 'o3',
    provider: 'openai',
    name: 'o3',
    capabilities: { text: true, reasoning: true, toolUse: true, json: true },
    iq: 5,
    speed: 2,
    metrics: { contextWindow: 200000, intelligenceIndex: 75 },
    releaseDate: '2025-04-01',
    status: 'all',
  },
  {
    id: 'openai-gpt-6-preview',
    value: 'gpt-6-preview',
    provider: 'openai',
    name: 'GPT-6 (Preview)',
    capabilities: { text: true, vision: true, reasoning: true, toolUse: true, json: true, audio: true },
    iq: 5,
    speed: 3,
    metrics: { contextWindow: 256000, intelligenceIndex: 80 },
    releaseDate: '2025-11-01',
    status: 'preview',
  },

  // Anthropic models
  {
    id: 'anthropic-claude-4-5-sonnet',
    value: 'claude-4-5-sonnet',
    provider: 'anthropic',
    name: 'Claude 4.5 Sonnet',
    alias: 'Sonnet 4.5',
    capabilities: { text: true, vision: true, reasoning: true, toolUse: true, json: true },
    iq: 5,
    speed: 4,
    metrics: { contextWindow: 200000, intelligenceIndex: 70 },
    releaseDate: '2025-08-01',
    status: 'latest',
  },
  {
    id: 'anthropic-claude-4-5-haiku',
    value: 'claude-4-5-haiku',
    provider: 'anthropic',
    name: 'Claude 4.5 Haiku',
    capabilities: { text: true, vision: true, toolUse: true, json: true },
    iq: 4,
    speed: 5,
    metrics: { contextWindow: 200000, intelligenceIndex: 55 },
    releaseDate: '2025-09-01',
    status: 'latest',
  },
  {
    id: 'anthropic-claude-3-5-sonnet',
    value: 'claude-3-5-sonnet',
    provider: 'anthropic',
    name: 'Claude 3.5 Sonnet',
    capabilities: { text: true, vision: true, toolUse: true, json: true },
    iq: 4,
    speed: 4,
    metrics: { contextWindow: 200000, intelligenceIndex: 60 },
    releaseDate: '2024-10-22',
    status: 'all',
  },
  {
    id: 'anthropic-claude-opus-5',
    value: 'claude-opus-5',
    provider: 'anthropic',
    name: 'Claude Opus 5 (Preview)',
    capabilities: { text: true, vision: true, reasoning: true, toolUse: true, json: true },
    iq: 5,
    speed: 2,
    metrics: { contextWindow: 200000, intelligenceIndex: 78 },
    releaseDate: '2025-11-15',
    status: 'preview',
  },

  // Google models
  {
    id: 'google-gemini-2-5-pro',
    value: 'gemini-2.5-pro',
    provider: 'google',
    name: 'Gemini 2.5 Pro',
    capabilities: { text: true, vision: true, reasoning: true, toolUse: true, json: true, audio: true },
    iq: 5,
    speed: 3,
    metrics: { contextWindow: 1000000, intelligenceIndex: 68 },
    releaseDate: '2025-03-25',
    status: 'latest',
  },
  {
    id: 'google-gemini-2-0-flash',
    value: 'gemini-2.0-flash',
    provider: 'google',
    name: 'Gemini 2.0 Flash',
    capabilities: { text: true, vision: true, toolUse: true, json: true },
    iq: 4,
    speed: 5,
    metrics: { contextWindow: 1000000, intelligenceIndex: 52 },
    releaseDate: '2025-02-05',
    status: 'all',
  },
  {
    id: 'google-gemini-3-preview',
    value: 'gemini-3-preview',
    provider: 'google',
    name: 'Gemini 3 (Preview)',
    capabilities: { text: true, vision: true, reasoning: true, toolUse: true, json: true, audio: true },
    iq: 5,
    speed: 4,
    metrics: { contextWindow: 2000000, intelligenceIndex: 82 },
    releaseDate: '2025-11-20',
    status: 'preview',
  },

  // xAI models
  {
    id: 'xai-grok-4',
    value: 'grok-4',
    provider: 'xai',
    name: 'Grok 4',
    capabilities: { text: true, vision: true, reasoning: true, toolUse: true, json: true },
    iq: 5,
    speed: 3,
    metrics: { contextWindow: 128000, intelligenceIndex: 65 },
    releaseDate: '2025-07-01',
    status: 'latest',
  },
  {
    id: 'xai-grok-3',
    value: 'grok-3',
    provider: 'xai',
    name: 'Grok 3',
    capabilities: { text: true, vision: true, toolUse: true, json: true },
    iq: 4,
    speed: 4,
    metrics: { contextWindow: 128000, intelligenceIndex: 58 },
    releaseDate: '2025-02-17',
    status: 'all',
  },
]

export const testManifest: Manifest = {
  version: 'v1.test123',
  etag: '"test-etag-abc123"',
  generatedAt: '2025-11-29T00:00:00.000Z',
  providers: testProviders,
  models: testModels,
}

export function createTestManifest(overrides?: Partial<Manifest>): Manifest {
  return {
    ...testManifest,
    ...overrides,
  }
}
