import type { ReasoningControl } from './types'

interface ReasoningGroupSpec {
  defaultModel: string
  model: string
  efforts: readonly string[] | undefined
}

const REASONING_GROUP_SPECS: Record<string, ReasoningGroupSpec> = {
  'ai2:olmo-3-1-32b-think': { defaultModel: 'olmo-3-1-32b-think', model: 'olmo-3-1-32b-think', efforts: ['low', 'medium', 'high'] },
  'ai2:olmo-3-7b-think': { defaultModel: 'olmo-3-7b-think', model: 'olmo-3-7b-think', efforts: ['low', 'medium', 'high'] },
  'ai21-labs:jamba-reasoning-3b': { defaultModel: 'jamba-reasoning-3b', model: 'jamba-reasoning-3b', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-235b-2507': { defaultModel: 'qwen3-235b-2507', model: 'qwen3-235b-2507', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-235b-a22b-2507': { defaultModel: 'qwen3-235b-a22b-2507', model: 'qwen3-235b-a22b-2507', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-30b-a3b-2507': { defaultModel: 'qwen3-30b-a3b-2507', model: 'qwen3-30b-a3b-2507', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-5-122b-a10b': { defaultModel: 'qwen3-5-122b-a10b-non-reasoning', model: 'qwen3-5-122b-a10b', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-5-27b': { defaultModel: 'qwen3-5-27b-non-reasoning', model: 'qwen3-5-27b', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-5-35b-a3b': { defaultModel: 'qwen3-5-35b-a3b-non-reasoning', model: 'qwen3-5-35b-a3b', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-5-397b-a17b': { defaultModel: 'qwen3-5-397b-a17b-non-reasoning', model: 'qwen3-5-397b-a17b', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-max': { defaultModel: 'qwen3-max', model: 'qwen3-max', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-next-80b-a3b': { defaultModel: 'qwen3-next-80b-a3b-reasoning', model: 'qwen3-next-80b-a3b-reasoning', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-omni-30b-a3b': { defaultModel: 'qwen3-omni-30b-a3b-reasoning', model: 'qwen3-omni-30b-a3b-reasoning', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-vl-235b-a22b': { defaultModel: 'qwen3-vl-235b-a22b-reasoning', model: 'qwen3-vl-235b-a22b-reasoning', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-vl-30b-a3b': { defaultModel: 'qwen3-vl-30b-a3b-reasoning', model: 'qwen3-vl-30b-a3b-reasoning', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-vl-32b': { defaultModel: 'qwen3-vl-32b-reasoning', model: 'qwen3-vl-32b-reasoning', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-vl-4b': { defaultModel: 'qwen3-vl-4b-reasoning', model: 'qwen3-vl-4b-reasoning', efforts: ['low', 'medium', 'high'] },
  'alibaba:qwen3-vl-8b': { defaultModel: 'qwen3-vl-8b-reasoning', model: 'qwen3-vl-8b-reasoning', efforts: ['low', 'medium', 'high'] },
  'anthropic:claude-4-5-haiku': { defaultModel: 'claude-4-5-haiku', model: 'claude-4-5-haiku-reasoning', efforts: ['high', 'max'] },
  'anthropic:claude-4-5-sonnet': { defaultModel: 'claude-4-5-sonnet', model: 'claude-4-5-sonnet-thinking', efforts: ['high', 'max'] },
  'anthropic:claude-opus-4-5': { defaultModel: 'claude-opus-4-5', model: 'claude-opus-4-5-thinking', efforts: ['high', 'max'] },
  'anthropic:claude-opus-4-6': { defaultModel: 'claude-opus-4-6', model: 'claude-opus-4-6-adaptive', efforts: ['low', 'medium', 'high', 'max'] },
  'anthropic:claude-sonnet-4-6': { defaultModel: 'claude-sonnet-4-6', model: 'claude-sonnet-4-6-adaptive', efforts: ['low', 'medium', 'high', 'max'] },
  'aws:nova-2-0-lite': { defaultModel: 'nova-2-0-lite', model: 'nova-2-0-lite-reasoning-low', efforts: ['low', 'medium', 'high'] },
  'aws:nova-2-0-omni': { defaultModel: 'nova-2-0-omni', model: 'nova-2-0-omni-reasoning-low', efforts: ['low', 'medium', 'high'] },
  'aws:nova-2-0-pro': { defaultModel: 'nova-2-0-pro', model: 'nova-2-0-pro', efforts: ['low', 'medium', 'high'] },
  'azure:claude-4-5-haiku': { defaultModel: 'claude-4-5-haiku', model: 'claude-4-5-haiku', efforts: ['low', 'medium', 'high'] },
  'azure:claude-4-5-sonnet': { defaultModel: 'claude-4-5-sonnet', model: 'claude-4-5-sonnet', efforts: ['low', 'medium', 'high'] },
  'azure:claude-opus-4-5': { defaultModel: 'claude-opus-4-5', model: 'claude-opus-4-5', efforts: ['high', 'max'] },
  'azure:gpt-5-mini': { defaultModel: 'gpt-5-mini', model: 'gpt-5-mini', efforts: ['minimal', 'low', 'medium', 'high'] },
  'azure:gpt-5-nano': { defaultModel: 'gpt-5-nano', model: 'gpt-5-nano', efforts: ['minimal', 'low', 'medium', 'high'] },
  'azure:gpt-5-pro': { defaultModel: 'gpt-5-pro', model: 'gpt-5-pro', efforts: ['minimal', 'low', 'medium', 'high'] },
  'azure:gpt-5.1': { defaultModel: 'gpt-5.1', model: 'gpt-5.1', efforts: ['low', 'medium', 'high'] },
  'azure:gpt-5.1-codex': { defaultModel: 'gpt-5.1-codex', model: 'gpt-5.1-codex', efforts: ['low', 'medium', 'high'] },
  'azure:gpt-5.2': { defaultModel: 'gpt-5.2', model: 'gpt-5.2', efforts: ['low', 'medium', 'high'] },
  'azure:gpt-5.2-codex': { defaultModel: 'gpt-5.2-codex', model: 'gpt-5.2-codex', efforts: ['low', 'medium', 'high'] },
  'azure:gpt-oss-120b': { defaultModel: 'gpt-oss-120b', model: 'gpt-oss-120b', efforts: ['low', 'medium', 'high'] },
  'azure:grok-4-fast': { defaultModel: 'grok-4-fast-non-reasoning', model: 'grok-4-fast-reasoning', efforts: undefined },
  'azure:phi-4': { defaultModel: 'phi-4', model: 'phi-4', efforts: ['low', 'medium', 'high'] },
  'azure:phi-4-mini': { defaultModel: 'phi-4-mini', model: 'phi-4-mini', efforts: ['low', 'medium', 'high'] },
  'baidu:ernie-5-0': { defaultModel: 'ernie-5-0-thinking-preview', model: 'ernie-5-0-thinking-preview', efforts: ['low', 'medium', 'high'] },
  'bytedance_seed:doubao-seed-1-8': { defaultModel: 'doubao-seed-1-8', model: 'doubao-seed-1-8', efforts: ['low', 'medium', 'high'] },
  'bytedance_seed:doubao-seed-code': { defaultModel: 'doubao-seed-code', model: 'doubao-seed-code', efforts: ['low', 'medium', 'high'] },
  'bytedance_seed:seed-oss-36b-instruct': { defaultModel: 'seed-oss-36b-instruct', model: 'seed-oss-36b-instruct', efforts: ['low', 'medium', 'high'] },
  'cerebras:gpt-oss-120b': { defaultModel: 'gpt-oss-120b', model: 'gpt-oss-120b', efforts: ['low', 'medium', 'high'] },
  'deepseek:deepseek-v3-2': { defaultModel: 'deepseek-v3-2', model: 'deepseek-v3-2-reasoning', efforts: undefined },
  'google:gemini-2-5-flash': { defaultModel: 'gemini-2-5-flash', model: 'gemini-2-5-flash', efforts: ['high', 'max'] },
  'google:gemini-2-5-flash-lite': { defaultModel: 'gemini-2-5-flash-lite', model: 'gemini-2-5-flash-lite', efforts: ['high', 'max'] },
  'google:gemini-2-5-pro': { defaultModel: 'gemini-2-5-pro', model: 'gemini-2-5-pro', efforts: ['high', 'max'] },
  'google:gemini-3-1-flash-lite-preview': { defaultModel: 'gemini-3-1-flash-lite-preview', model: 'gemini-3-1-flash-lite-preview', efforts: ['low', 'medium', 'high'] },
  'google:gemini-3-1-pro-preview': { defaultModel: 'gemini-3-1-pro-preview', model: 'gemini-3-1-pro-preview', efforts: ['low', 'medium', 'high'] },
  'google:gemini-3-flash': { defaultModel: 'gemini-3-flash', model: 'gemini-3-flash-reasoning', efforts: ['low', 'high'] },
  'google:gemini-3-pro': { defaultModel: 'gemini-3-pro', model: 'gemini-3-pro', efforts: ['low', 'high'] },
  'google:gemini-3-pro-low': { defaultModel: 'gemini-3-pro-low', model: 'gemini-3-pro-low', efforts: ['low', 'high'] },
  'groq:openai/gpt-oss-120b': { defaultModel: 'openai/gpt-oss-120b', model: 'openai/gpt-oss-120b', efforts: ['low', 'medium', 'high'] },
  'groq:openai/gpt-oss-20b': { defaultModel: 'openai/gpt-oss-20b', model: 'openai/gpt-oss-20b', efforts: ['low', 'medium', 'high'] },
  'inception:mercury-2': { defaultModel: 'mercury-2', model: 'mercury-2', efforts: ['low', 'medium', 'high'] },
  'inclusionai:ling-1t': { defaultModel: 'ling-1t', model: 'ling-1t', efforts: ['low', 'medium', 'high'] },
  'inclusionai:ling-flash-2-0': { defaultModel: 'ling-flash-2-0', model: 'ling-flash-2-0', efforts: ['low', 'medium', 'high'] },
  'inclusionai:ling-mini-2-0': { defaultModel: 'ling-mini-2-0', model: 'ling-mini-2-0', efforts: ['low', 'medium', 'high'] },
  'inclusionai:ring-flash-2-0': { defaultModel: 'ring-flash-2-0', model: 'ring-flash-2-0', efforts: ['low', 'medium', 'high'] },
  'kimi:kimi-k2-5': { defaultModel: 'kimi-k2-5-non-reasoning', model: 'kimi-k2-5', efforts: undefined },
  'korea-telecom:mi-dm-k-2-5-pro-dec28': { defaultModel: 'mi-dm-k-2-5-pro-dec28', model: 'mi-dm-k-2-5-pro-dec28', efforts: ['low', 'medium', 'high'] },
  'lg:k-exaone': { defaultModel: 'k-exaone-non-reasoning', model: 'k-exaone', efforts: ['low', 'medium', 'high'] },
  'liquidai:lfm2-5-1-2b': { defaultModel: 'lfm2-5-1-2b-thinking', model: 'lfm2-5-1-2b-thinking', efforts: ['low', 'medium', 'high'] },
  'mbzuai:k2-think-v2': { defaultModel: 'k2-think-v2', model: 'k2-think-v2', efforts: ['low', 'medium', 'high'] },
  'mbzuai:k2-v2': { defaultModel: 'k2-v2', model: 'k2-v2', efforts: ['low', 'medium', 'high'] },
  'mbzuai:k2-v2-low': { defaultModel: 'k2-v2-low', model: 'k2-v2-low', efforts: ['low', 'medium', 'high'] },
  'mbzuai:k2-v2-medium': { defaultModel: 'k2-v2-medium', model: 'k2-v2-medium', efforts: ['low', 'medium', 'high'] },
  'meta:llama-4-maverick': { defaultModel: 'llama-4-maverick', model: 'llama-4-maverick', efforts: ['low', 'medium', 'high'] },
  'meta:llama-4-scout': { defaultModel: 'llama-4-scout', model: 'llama-4-scout', efforts: ['low', 'medium', 'high'] },
  'motif-technologies:motif-2-12-7b': { defaultModel: 'motif-2-12-7b', model: 'motif-2-12-7b', efforts: ['low', 'medium', 'high'] },
  'naver:hyperclova-x-seed-think-32b': { defaultModel: 'hyperclova-x-seed-think-32b', model: 'hyperclova-x-seed-think-32b', efforts: ['low', 'medium', 'high'] },
  'nous-research:deephermes-3-llama-3-1-8b-preview': { defaultModel: 'deephermes-3-llama-3-1-8b-preview', model: 'deephermes-3-llama-3-1-8b-preview', efforts: ['low', 'medium', 'high'] },
  'nous-research:hermes-4-405b': { defaultModel: 'hermes-4-405b', model: 'hermes-4-405b', efforts: ['low', 'medium', 'high'] },
  'nous-research:hermes-4-70b': { defaultModel: 'hermes-4-70b', model: 'hermes-4-70b', efforts: ['low', 'medium', 'high'] },
  'nvidia:llama-3-1-nemotron-nano-4b-v1-1': { defaultModel: 'llama-3-1-nemotron-nano-4b-v1-1', model: 'llama-3-1-nemotron-nano-4b-v1-1', efforts: ['low', 'medium', 'high'] },
  'nvidia:llama-3-3-nemotron-super-49b': { defaultModel: 'llama-3-3-nemotron-super-49b', model: 'llama-3-3-nemotron-super-49b', efforts: ['low', 'medium', 'high'] },
  'nvidia:llama-nemotron-super-49b-v1-5': { defaultModel: 'llama-nemotron-super-49b-v1-5', model: 'llama-nemotron-super-49b-v1-5', efforts: ['low', 'medium', 'high'] },
  'nvidia:llama-nemotron-ultra': { defaultModel: 'llama-nemotron-ultra', model: 'llama-nemotron-ultra', efforts: ['low', 'medium', 'high'] },
  'nvidia:nvidia-nemotron-3-nano-30b-a3b': { defaultModel: 'nvidia-nemotron-3-nano-30b-a3b', model: 'nvidia-nemotron-3-nano-30b-a3b-reasoning', efforts: ['low', 'medium', 'high'] },
  'nvidia:nvidia-nemotron-nano-12b-v2-vl': { defaultModel: 'nvidia-nemotron-nano-12b-v2-vl', model: 'nvidia-nemotron-nano-12b-v2-vl-reasoning', efforts: ['low', 'medium', 'high'] },
  'nvidia:nvidia-nemotron-nano-9b-v2': { defaultModel: 'nvidia-nemotron-nano-9b-v2', model: 'nvidia-nemotron-nano-9b-v2', efforts: ['low', 'medium', 'high'] },
  'openai:gpt-5-1-codex-mini': { defaultModel: 'gpt-5-1-codex-mini', model: 'gpt-5-1-codex-mini', efforts: ['low', 'medium', 'high'] },
  'openai:gpt-5-2': { defaultModel: 'gpt-5-2-non-reasoning', model: 'gpt-5-2', efforts: ['low', 'medium', 'high', 'xhigh'] },
  'openai:gpt-5-2-codex': { defaultModel: 'gpt-5-2-codex', model: 'gpt-5-2-codex', efforts: ['low', 'medium', 'high', 'xhigh'] },
  'openai:gpt-5-2-medium': { defaultModel: 'gpt-5-2-medium', model: 'gpt-5-2-medium', efforts: ['minimal', 'low', 'medium', 'high'] },
  'openai:gpt-5-3-codex': { defaultModel: 'gpt-5-3-codex', model: 'gpt-5-3-codex', efforts: ['low', 'medium', 'high', 'xhigh'] },
  'openai:gpt-5-mini': { defaultModel: 'gpt-5-mini', model: 'gpt-5-mini', efforts: ['minimal', 'low', 'medium', 'high'] },
  'openai:gpt-5-mini-medium': { defaultModel: 'gpt-5-mini-medium', model: 'gpt-5-mini-medium', efforts: ['minimal', 'low', 'medium', 'high'] },
  'openai:gpt-5-mini-minimal': { defaultModel: 'gpt-5-mini-minimal', model: 'gpt-5-mini-minimal', efforts: ['minimal', 'low', 'medium', 'high'] },
  'openai:gpt-5-minimal': { defaultModel: 'gpt-5-minimal', model: 'gpt-5-minimal', efforts: ['minimal', 'low', 'medium', 'high'] },
  'openai:gpt-5-nano': { defaultModel: 'gpt-5-nano', model: 'gpt-5-nano', efforts: ['minimal', 'low', 'medium', 'high'] },
  'openai:gpt-5-nano-medium': { defaultModel: 'gpt-5-nano-medium', model: 'gpt-5-nano-medium', efforts: ['minimal', 'low', 'medium', 'high'] },
  'openai:gpt-5-nano-minimal': { defaultModel: 'gpt-5-nano-minimal', model: 'gpt-5-nano-minimal', efforts: ['minimal', 'low', 'medium', 'high'] },
  'openai:gpt-oss-120b': { defaultModel: 'gpt-oss-120b', model: 'gpt-oss-120b', efforts: ['low', 'medium', 'high'] },
  'openai:gpt-oss-120b-low': { defaultModel: 'gpt-oss-120b-low', model: 'gpt-oss-120b-low', efforts: ['low', 'medium', 'high'] },
  'openai:gpt-oss-20b': { defaultModel: 'gpt-oss-20b', model: 'gpt-oss-20b', efforts: ['low', 'medium', 'high'] },
  'openai:gpt-oss-20b-low': { defaultModel: 'gpt-oss-20b-low', model: 'gpt-oss-20b-low', efforts: ['low', 'medium', 'high'] },
  'prime-intellect:intellect-3': { defaultModel: 'intellect-3', model: 'intellect-3', efforts: ['low', 'medium', 'high'] },
  'reka-ai:reka-flash-3': { defaultModel: 'reka-flash-3', model: 'reka-flash-3', efforts: ['low', 'medium', 'high'] },
  'servicenow:apriel-v1-6-15b-thinker': { defaultModel: 'apriel-v1-6-15b-thinker', model: 'apriel-v1-6-15b-thinker', efforts: ['low', 'medium', 'high'] },
  'stepfun:step3-vl-10b': { defaultModel: 'step3-vl-10b', model: 'step3-vl-10b', efforts: ['low', 'medium', 'high'] },
  'tii-uae:falcon-h1r-7b': { defaultModel: 'falcon-h1r-7b', model: 'falcon-h1r-7b', efforts: ['low', 'medium', 'high'] },
  'trillionlabs:tri-21b-think-preview': { defaultModel: 'tri-21b-think-preview', model: 'tri-21b-think-preview', efforts: ['low', 'medium', 'high'] },
  'trillionlabs:tri-21b-think-v0-5': { defaultModel: 'tri-21b-think-v0-5', model: 'tri-21b-think-v0-5', efforts: ['low', 'medium', 'high'] },
  'upstage:solar-open-100b': { defaultModel: 'solar-open-100b-reasoning', model: 'solar-open-100b-reasoning', efforts: ['low', 'medium', 'high'] },
  'upstage:solar-pro-2': { defaultModel: 'solar-pro-2', model: 'solar-pro-2', efforts: ['low', 'medium', 'high'] },
  'xai:grok-4-1-fast': { defaultModel: 'grok-4-1-fast', model: 'grok-4-1-fast-reasoning', efforts: undefined },
  'xai:grok-4-fast': { defaultModel: 'grok-4-fast', model: 'grok-4-fast-reasoning', efforts: undefined },
  'xiaomi:mimo-v2-0206': { defaultModel: 'mimo-v2-0206', model: 'mimo-v2-0206', efforts: ['low', 'medium', 'high'] },
  'xiaomi:mimo-v2-flash': { defaultModel: 'mimo-v2-flash', model: 'mimo-v2-flash-reasoning', efforts: ['low', 'medium', 'high'] },
  'zai:glm-4-6v': { defaultModel: 'glm-4-6v', model: 'glm-4-6v-reasoning', efforts: undefined },
  'zai:glm-4-7': { defaultModel: 'glm-4-7-non-reasoning', model: 'glm-4-7', efforts: undefined },
  'zai:glm-4-7-flash': { defaultModel: 'glm-4-7-flash-non-reasoning', model: 'glm-4-7-flash', efforts: undefined },
  'zai:glm-5': { defaultModel: 'glm-5-non-reasoning', model: 'glm-5', efforts: undefined },
}

const MODEL_TO_REASONING_GROUP: Record<string, string> = {
  'ai2:olmo-3-1-32b-think': 'ai2:olmo-3-1-32b-think',
  'ai2:olmo-3-7b-think': 'ai2:olmo-3-7b-think',
  'ai21-labs:jamba-reasoning-3b': 'ai21-labs:jamba-reasoning-3b',
  'alibaba:qwen3-235b-2507': 'alibaba:qwen3-235b-2507',
  'alibaba:qwen3-235b-a22b-2507': 'alibaba:qwen3-235b-a22b-2507',
  'alibaba:qwen3-30b-a3b-2507': 'alibaba:qwen3-30b-a3b-2507',
  'alibaba:qwen3-5-122b-a10b': 'alibaba:qwen3-5-122b-a10b',
  'alibaba:qwen3-5-122b-a10b-non-reasoning': 'alibaba:qwen3-5-122b-a10b',
  'alibaba:qwen3-5-27b': 'alibaba:qwen3-5-27b',
  'alibaba:qwen3-5-27b-non-reasoning': 'alibaba:qwen3-5-27b',
  'alibaba:qwen3-5-35b-a3b': 'alibaba:qwen3-5-35b-a3b',
  'alibaba:qwen3-5-35b-a3b-non-reasoning': 'alibaba:qwen3-5-35b-a3b',
  'alibaba:qwen3-5-397b-a17b': 'alibaba:qwen3-5-397b-a17b',
  'alibaba:qwen3-5-397b-a17b-non-reasoning': 'alibaba:qwen3-5-397b-a17b',
  'alibaba:qwen3-max': 'alibaba:qwen3-max',
  'alibaba:qwen3-max-thinking-preview': 'alibaba:qwen3-max',
  'alibaba:qwen3-next-80b-a3b-reasoning': 'alibaba:qwen3-next-80b-a3b',
  'alibaba:qwen3-omni-30b-a3b-reasoning': 'alibaba:qwen3-omni-30b-a3b',
  'alibaba:qwen3-vl-235b-a22b-reasoning': 'alibaba:qwen3-vl-235b-a22b',
  'alibaba:qwen3-vl-30b-a3b-reasoning': 'alibaba:qwen3-vl-30b-a3b',
  'alibaba:qwen3-vl-32b-reasoning': 'alibaba:qwen3-vl-32b',
  'alibaba:qwen3-vl-4b-reasoning': 'alibaba:qwen3-vl-4b',
  'alibaba:qwen3-vl-8b-reasoning': 'alibaba:qwen3-vl-8b',
  'anthropic:claude-4-5-haiku': 'anthropic:claude-4-5-haiku',
  'anthropic:claude-4-5-haiku-reasoning': 'anthropic:claude-4-5-haiku',
  'anthropic:claude-4-5-sonnet': 'anthropic:claude-4-5-sonnet',
  'anthropic:claude-4-5-sonnet-thinking': 'anthropic:claude-4-5-sonnet',
  'anthropic:claude-opus-4-5': 'anthropic:claude-opus-4-5',
  'anthropic:claude-opus-4-5-thinking': 'anthropic:claude-opus-4-5',
  'anthropic:claude-opus-4-6': 'anthropic:claude-opus-4-6',
  'anthropic:claude-opus-4-6-adaptive': 'anthropic:claude-opus-4-6',
  'anthropic:claude-sonnet-4-6': 'anthropic:claude-sonnet-4-6',
  'anthropic:claude-sonnet-4-6-adaptive': 'anthropic:claude-sonnet-4-6',
  'anthropic:claude-sonnet-4-6-non-reasoning-low-effort': 'anthropic:claude-sonnet-4-6',
  'aws:nova-2-0-lite': 'aws:nova-2-0-lite',
  'aws:nova-2-0-lite-reasoning-low': 'aws:nova-2-0-lite',
  'aws:nova-2-0-lite-reasoning-medium': 'aws:nova-2-0-lite',
  'aws:nova-2-0-omni': 'aws:nova-2-0-omni',
  'aws:nova-2-0-omni-reasoning-low': 'aws:nova-2-0-omni',
  'aws:nova-2-0-omni-reasoning-medium': 'aws:nova-2-0-omni',
  'aws:nova-2-0-pro': 'aws:nova-2-0-pro',
  'aws:nova-2-0-pro-reasoning-low': 'aws:nova-2-0-pro',
  'aws:nova-2-0-pro-reasoning-medium': 'aws:nova-2-0-pro',
  'azure:claude-4-5-haiku': 'azure:claude-4-5-haiku',
  'azure:claude-4-5-sonnet': 'azure:claude-4-5-sonnet',
  'azure:claude-opus-4-5': 'azure:claude-opus-4-5',
  'azure:gpt-5-mini': 'azure:gpt-5-mini',
  'azure:gpt-5-nano': 'azure:gpt-5-nano',
  'azure:gpt-5-pro': 'azure:gpt-5-pro',
  'azure:gpt-5.1': 'azure:gpt-5.1',
  'azure:gpt-5.1-codex': 'azure:gpt-5.1-codex',
  'azure:gpt-5.2': 'azure:gpt-5.2',
  'azure:gpt-5.2-codex': 'azure:gpt-5.2-codex',
  'azure:gpt-oss-120b': 'azure:gpt-oss-120b',
  'azure:grok-4-fast-non-reasoning': 'azure:grok-4-fast',
  'azure:grok-4-fast-reasoning': 'azure:grok-4-fast',
  'azure:phi-4': 'azure:phi-4',
  'azure:phi-4-mini': 'azure:phi-4-mini',
  'baidu:ernie-5-0-thinking-preview': 'baidu:ernie-5-0',
  'bytedance_seed:doubao-seed-1-8': 'bytedance_seed:doubao-seed-1-8',
  'bytedance_seed:doubao-seed-code': 'bytedance_seed:doubao-seed-code',
  'bytedance_seed:seed-oss-36b-instruct': 'bytedance_seed:seed-oss-36b-instruct',
  'cerebras:gpt-oss-120b': 'cerebras:gpt-oss-120b',
  'deepseek:deepseek-v3-2': 'deepseek:deepseek-v3-2',
  'deepseek:deepseek-v3-2-reasoning': 'deepseek:deepseek-v3-2',
  'google:gemini-2-5-flash': 'google:gemini-2-5-flash',
  'google:gemini-2-5-flash-lite': 'google:gemini-2-5-flash-lite',
  'google:gemini-2-5-pro': 'google:gemini-2-5-pro',
  'google:gemini-3-1-flash-lite-preview': 'google:gemini-3-1-flash-lite-preview',
  'google:gemini-3-1-pro-preview': 'google:gemini-3-1-pro-preview',
  'google:gemini-3-flash': 'google:gemini-3-flash',
  'google:gemini-3-flash-reasoning': 'google:gemini-3-flash',
  'google:gemini-3-pro': 'google:gemini-3-pro',
  'google:gemini-3-pro-low': 'google:gemini-3-pro-low',
  'groq:openai/gpt-oss-120b': 'groq:openai/gpt-oss-120b',
  'groq:openai/gpt-oss-20b': 'groq:openai/gpt-oss-20b',
  'inception:mercury-2': 'inception:mercury-2',
  'inclusionai:ling-1t': 'inclusionai:ling-1t',
  'inclusionai:ling-flash-2-0': 'inclusionai:ling-flash-2-0',
  'inclusionai:ling-mini-2-0': 'inclusionai:ling-mini-2-0',
  'inclusionai:ring-flash-2-0': 'inclusionai:ring-flash-2-0',
  'kimi:kimi-k2-5': 'kimi:kimi-k2-5',
  'kimi:kimi-k2-5-non-reasoning': 'kimi:kimi-k2-5',
  'korea-telecom:mi-dm-k-2-5-pro-dec28': 'korea-telecom:mi-dm-k-2-5-pro-dec28',
  'lg:k-exaone': 'lg:k-exaone',
  'lg:k-exaone-non-reasoning': 'lg:k-exaone',
  'liquidai:lfm2-5-1-2b-thinking': 'liquidai:lfm2-5-1-2b',
  'mbzuai:k2-think-v2': 'mbzuai:k2-think-v2',
  'mbzuai:k2-v2': 'mbzuai:k2-v2',
  'mbzuai:k2-v2-low': 'mbzuai:k2-v2-low',
  'mbzuai:k2-v2-medium': 'mbzuai:k2-v2-medium',
  'meta:llama-4-maverick': 'meta:llama-4-maverick',
  'meta:llama-4-scout': 'meta:llama-4-scout',
  'motif-technologies:motif-2-12-7b': 'motif-technologies:motif-2-12-7b',
  'naver:hyperclova-x-seed-think-32b': 'naver:hyperclova-x-seed-think-32b',
  'nous-research:deephermes-3-llama-3-1-8b-preview': 'nous-research:deephermes-3-llama-3-1-8b-preview',
  'nous-research:hermes-4-405b': 'nous-research:hermes-4-405b',
  'nous-research:hermes-4-70b': 'nous-research:hermes-4-70b',
  'nvidia:llama-3-1-nemotron-nano-4b-v1-1': 'nvidia:llama-3-1-nemotron-nano-4b-v1-1',
  'nvidia:llama-3-3-nemotron-super-49b': 'nvidia:llama-3-3-nemotron-super-49b',
  'nvidia:llama-nemotron-super-49b-v1-5': 'nvidia:llama-nemotron-super-49b-v1-5',
  'nvidia:llama-nemotron-ultra': 'nvidia:llama-nemotron-ultra',
  'nvidia:nvidia-nemotron-3-nano-30b-a3b': 'nvidia:nvidia-nemotron-3-nano-30b-a3b',
  'nvidia:nvidia-nemotron-3-nano-30b-a3b-reasoning': 'nvidia:nvidia-nemotron-3-nano-30b-a3b',
  'nvidia:nvidia-nemotron-nano-12b-v2-vl': 'nvidia:nvidia-nemotron-nano-12b-v2-vl',
  'nvidia:nvidia-nemotron-nano-12b-v2-vl-reasoning': 'nvidia:nvidia-nemotron-nano-12b-v2-vl',
  'nvidia:nvidia-nemotron-nano-9b-v2': 'nvidia:nvidia-nemotron-nano-9b-v2',
  'openai:gpt-5-1-codex-mini': 'openai:gpt-5-1-codex-mini',
  'openai:gpt-5-2': 'openai:gpt-5-2',
  'openai:gpt-5-2-codex': 'openai:gpt-5-2-codex',
  'openai:gpt-5-2-medium': 'openai:gpt-5-2-medium',
  'openai:gpt-5-2-non-reasoning': 'openai:gpt-5-2',
  'openai:gpt-5-3-codex': 'openai:gpt-5-3-codex',
  'openai:gpt-5-mini': 'openai:gpt-5-mini',
  'openai:gpt-5-mini-medium': 'openai:gpt-5-mini-medium',
  'openai:gpt-5-mini-minimal': 'openai:gpt-5-mini-minimal',
  'openai:gpt-5-minimal': 'openai:gpt-5-minimal',
  'openai:gpt-5-nano': 'openai:gpt-5-nano',
  'openai:gpt-5-nano-medium': 'openai:gpt-5-nano-medium',
  'openai:gpt-5-nano-minimal': 'openai:gpt-5-nano-minimal',
  'openai:gpt-oss-120b': 'openai:gpt-oss-120b',
  'openai:gpt-oss-120b-low': 'openai:gpt-oss-120b-low',
  'openai:gpt-oss-20b': 'openai:gpt-oss-20b',
  'openai:gpt-oss-20b-low': 'openai:gpt-oss-20b-low',
  'prime-intellect:intellect-3': 'prime-intellect:intellect-3',
  'reka-ai:reka-flash-3': 'reka-ai:reka-flash-3',
  'servicenow:apriel-v1-6-15b-thinker': 'servicenow:apriel-v1-6-15b-thinker',
  'stepfun:step3-vl-10b': 'stepfun:step3-vl-10b',
  'tii-uae:falcon-h1r-7b': 'tii-uae:falcon-h1r-7b',
  'trillionlabs:tri-21b-think-preview': 'trillionlabs:tri-21b-think-preview',
  'trillionlabs:tri-21b-think-v0-5': 'trillionlabs:tri-21b-think-v0-5',
  'upstage:solar-open-100b-reasoning': 'upstage:solar-open-100b',
  'upstage:solar-pro-2': 'upstage:solar-pro-2',
  'xai:grok-4-1-fast': 'xai:grok-4-1-fast',
  'xai:grok-4-1-fast-reasoning': 'xai:grok-4-1-fast',
  'xai:grok-4-fast': 'xai:grok-4-fast',
  'xai:grok-4-fast-reasoning': 'xai:grok-4-fast',
  'xiaomi:mimo-v2-0206': 'xiaomi:mimo-v2-0206',
  'xiaomi:mimo-v2-flash': 'xiaomi:mimo-v2-flash',
  'xiaomi:mimo-v2-flash-reasoning': 'xiaomi:mimo-v2-flash',
  'zai:glm-4-6v': 'zai:glm-4-6v',
  'zai:glm-4-6v-reasoning': 'zai:glm-4-6v',
  'zai:glm-4-7': 'zai:glm-4-7',
  'zai:glm-4-7-flash': 'zai:glm-4-7-flash',
  'zai:glm-4-7-flash-non-reasoning': 'zai:glm-4-7-flash',
  'zai:glm-4-7-non-reasoning': 'zai:glm-4-7',
  'zai:glm-5': 'zai:glm-5',
  'zai:glm-5-non-reasoning': 'zai:glm-5',
}

function keyOf(provider: string, model: string): string {
  return `${provider.toLowerCase()}:${model.toLowerCase()}`
}

function buildControl(spec: ReasoningGroupSpec): ReasoningControl {
  const options = [{ id: 'default', model: spec.defaultModel }] as ReasoningControl['options']

  if (spec.efforts && spec.efforts.length > 0) {
    for (const effort of spec.efforts) {
      options.push({
        id: effort,
        model: spec.model,
        effort,
      })
    }
  }
  else if (spec.model !== spec.defaultModel) {
    options.push({
      id: 'thinking',
      model: spec.model,
    })
  }

  return {
    default: 'default',
    options,
  }
}

export function getModelReasoningControl(provider: string, model: string): ReasoningControl | undefined {
  const modelKey = keyOf(provider, model)
  const groupKey = MODEL_TO_REASONING_GROUP[modelKey]
  if (!groupKey)
    return undefined

  const spec = REASONING_GROUP_SPECS[groupKey]
  if (!spec)
    return undefined

  return buildControl(spec)
}
