import type { ReasoningControl } from './types'

interface ReasoningGroupSpec {
  default: ReasoningControl['default']
  options: ReasoningControl['options']
}

const REASONING_GROUP_SPECS: Record<string, ReasoningGroupSpec> = {
  'ai2:olmo-3-1-32b-think': { default: 'default', options: [{ id: 'default', model: 'olmo-3-1-32b-think' }, { id: 'low', model: 'olmo-3-1-32b-think', effort: 'low' }, { id: 'medium', model: 'olmo-3-1-32b-think', effort: 'medium' }, { id: 'high', model: 'olmo-3-1-32b-think', effort: 'high' }] },
  'ai2:olmo-3-7b-think': { default: 'default', options: [{ id: 'default', model: 'olmo-3-7b-think' }, { id: 'low', model: 'olmo-3-7b-think', effort: 'low' }, { id: 'medium', model: 'olmo-3-7b-think', effort: 'medium' }, { id: 'high', model: 'olmo-3-7b-think', effort: 'high' }] },
  'ai21-labs:jamba-reasoning-3b': { default: 'default', options: [{ id: 'default', model: 'jamba-reasoning-3b' }, { id: 'low', model: 'jamba-reasoning-3b', effort: 'low' }, { id: 'medium', model: 'jamba-reasoning-3b', effort: 'medium' }, { id: 'high', model: 'jamba-reasoning-3b', effort: 'high' }] },
  'alibaba:qwen3-235b-2507': { default: 'default', options: [{ id: 'default', model: 'qwen3-235b-2507' }, { id: 'low', model: 'qwen3-235b-2507', effort: 'low' }, { id: 'medium', model: 'qwen3-235b-2507', effort: 'medium' }, { id: 'high', model: 'qwen3-235b-2507', effort: 'high' }] },
  'alibaba:qwen3-235b-a22b-2507': { default: 'default', options: [{ id: 'default', model: 'qwen3-235b-a22b-2507' }, { id: 'low', model: 'qwen3-235b-a22b-2507', effort: 'low' }, { id: 'medium', model: 'qwen3-235b-a22b-2507', effort: 'medium' }, { id: 'high', model: 'qwen3-235b-a22b-2507', effort: 'high' }] },
  'alibaba:qwen3-30b-a3b-2507': { default: 'default', options: [{ id: 'default', model: 'qwen3-30b-a3b-2507' }, { id: 'low', model: 'qwen3-30b-a3b-2507', effort: 'low' }, { id: 'medium', model: 'qwen3-30b-a3b-2507', effort: 'medium' }, { id: 'high', model: 'qwen3-30b-a3b-2507', effort: 'high' }] },
  'alibaba:qwen3-5-122b-a10b': { default: 'default', options: [{ id: 'default', model: 'qwen3-5-122b-a10b-non-reasoning' }, { id: 'low', model: 'qwen3-5-122b-a10b', effort: 'low' }, { id: 'medium', model: 'qwen3-5-122b-a10b', effort: 'medium' }, { id: 'high', model: 'qwen3-5-122b-a10b', effort: 'high' }] },
  'alibaba:qwen3-5-27b': { default: 'default', options: [{ id: 'default', model: 'qwen3-5-27b-non-reasoning' }, { id: 'low', model: 'qwen3-5-27b', effort: 'low' }, { id: 'medium', model: 'qwen3-5-27b', effort: 'medium' }, { id: 'high', model: 'qwen3-5-27b', effort: 'high' }] },
  'alibaba:qwen3-5-35b-a3b': { default: 'default', options: [{ id: 'default', model: 'qwen3-5-35b-a3b-non-reasoning' }, { id: 'low', model: 'qwen3-5-35b-a3b', effort: 'low' }, { id: 'medium', model: 'qwen3-5-35b-a3b', effort: 'medium' }, { id: 'high', model: 'qwen3-5-35b-a3b', effort: 'high' }] },
  'alibaba:qwen3-5-397b-a17b': { default: 'default', options: [{ id: 'default', model: 'qwen3-5-397b-a17b-non-reasoning' }, { id: 'low', model: 'qwen3-5-397b-a17b', effort: 'low' }, { id: 'medium', model: 'qwen3-5-397b-a17b', effort: 'medium' }, { id: 'high', model: 'qwen3-5-397b-a17b', effort: 'high' }] },
  'alibaba:qwen3-max': { default: 'default', options: [{ id: 'default', model: 'qwen3-max' }, { id: 'low', model: 'qwen3-max', effort: 'low' }, { id: 'medium', model: 'qwen3-max', effort: 'medium' }, { id: 'high', model: 'qwen3-max', effort: 'high' }] },
  'alibaba:qwen3-next-80b-a3b': { default: 'default', options: [{ id: 'default', model: 'qwen3-next-80b-a3b-reasoning' }, { id: 'low', model: 'qwen3-next-80b-a3b-reasoning', effort: 'low' }, { id: 'medium', model: 'qwen3-next-80b-a3b-reasoning', effort: 'medium' }, { id: 'high', model: 'qwen3-next-80b-a3b-reasoning', effort: 'high' }] },
  'alibaba:qwen3-omni-30b-a3b': { default: 'default', options: [{ id: 'default', model: 'qwen3-omni-30b-a3b-reasoning' }, { id: 'low', model: 'qwen3-omni-30b-a3b-reasoning', effort: 'low' }, { id: 'medium', model: 'qwen3-omni-30b-a3b-reasoning', effort: 'medium' }, { id: 'high', model: 'qwen3-omni-30b-a3b-reasoning', effort: 'high' }] },
  'alibaba:qwen3-vl-235b-a22b': { default: 'default', options: [{ id: 'default', model: 'qwen3-vl-235b-a22b-reasoning' }, { id: 'low', model: 'qwen3-vl-235b-a22b-reasoning', effort: 'low' }, { id: 'medium', model: 'qwen3-vl-235b-a22b-reasoning', effort: 'medium' }, { id: 'high', model: 'qwen3-vl-235b-a22b-reasoning', effort: 'high' }] },
  'alibaba:qwen3-vl-30b-a3b': { default: 'default', options: [{ id: 'default', model: 'qwen3-vl-30b-a3b-reasoning' }, { id: 'low', model: 'qwen3-vl-30b-a3b-reasoning', effort: 'low' }, { id: 'medium', model: 'qwen3-vl-30b-a3b-reasoning', effort: 'medium' }, { id: 'high', model: 'qwen3-vl-30b-a3b-reasoning', effort: 'high' }] },
  'alibaba:qwen3-vl-32b': { default: 'default', options: [{ id: 'default', model: 'qwen3-vl-32b-reasoning' }, { id: 'low', model: 'qwen3-vl-32b-reasoning', effort: 'low' }, { id: 'medium', model: 'qwen3-vl-32b-reasoning', effort: 'medium' }, { id: 'high', model: 'qwen3-vl-32b-reasoning', effort: 'high' }] },
  'alibaba:qwen3-vl-4b': { default: 'default', options: [{ id: 'default', model: 'qwen3-vl-4b-reasoning' }, { id: 'low', model: 'qwen3-vl-4b-reasoning', effort: 'low' }, { id: 'medium', model: 'qwen3-vl-4b-reasoning', effort: 'medium' }, { id: 'high', model: 'qwen3-vl-4b-reasoning', effort: 'high' }] },
  'alibaba:qwen3-vl-8b': { default: 'default', options: [{ id: 'default', model: 'qwen3-vl-8b-reasoning' }, { id: 'low', model: 'qwen3-vl-8b-reasoning', effort: 'low' }, { id: 'medium', model: 'qwen3-vl-8b-reasoning', effort: 'medium' }, { id: 'high', model: 'qwen3-vl-8b-reasoning', effort: 'high' }] },
  'anthropic:claude-4-5-haiku': { default: 'default', options: [{ id: 'default', model: 'claude-4-5-haiku' }, { id: 'high', model: 'claude-4-5-haiku-reasoning', effort: 'high' }, { id: 'max', model: 'claude-4-5-haiku-reasoning', effort: 'max' }] },
  'anthropic:claude-4-5-sonnet': { default: 'default', options: [{ id: 'default', model: 'claude-4-5-sonnet' }, { id: 'high', model: 'claude-4-5-sonnet-thinking', effort: 'high' }, { id: 'max', model: 'claude-4-5-sonnet-thinking', effort: 'max' }] },
  'anthropic:claude-opus-4-5': { default: 'default', options: [{ id: 'default', model: 'claude-opus-4-5' }, { id: 'high', model: 'claude-opus-4-5-thinking', effort: 'high' }, { id: 'max', model: 'claude-opus-4-5-thinking', effort: 'max' }] },
  'anthropic:claude-opus-4-6': { default: 'default', options: [{ id: 'default', model: 'claude-opus-4-6' }, { id: 'low', model: 'claude-opus-4-6-adaptive', effort: 'low' }, { id: 'medium', model: 'claude-opus-4-6-adaptive', effort: 'medium' }, { id: 'high', model: 'claude-opus-4-6-adaptive', effort: 'high' }, { id: 'max', model: 'claude-opus-4-6-adaptive', effort: 'max' }] },
  'anthropic:claude-sonnet-4-6': { default: 'default', options: [{ id: 'default', model: 'claude-sonnet-4-6' }, { id: 'low', model: 'claude-sonnet-4-6-adaptive', effort: 'low' }, { id: 'medium', model: 'claude-sonnet-4-6-adaptive', effort: 'medium' }, { id: 'high', model: 'claude-sonnet-4-6-adaptive', effort: 'high' }, { id: 'max', model: 'claude-sonnet-4-6-adaptive', effort: 'max' }] },
  'aws:nova-2-0-lite': { default: 'default', options: [{ id: 'default', model: 'nova-2-0-lite' }, { id: 'low', model: 'nova-2-0-lite-reasoning-low', effort: 'low' }, { id: 'medium', model: 'nova-2-0-lite-reasoning-medium', effort: 'medium' }, { id: 'high', model: 'nova-2-0-lite-reasoning-low', effort: 'high' }] },
  'aws:nova-2-0-omni': { default: 'default', options: [{ id: 'default', model: 'nova-2-0-omni' }, { id: 'low', model: 'nova-2-0-omni-reasoning-low', effort: 'low' }, { id: 'medium', model: 'nova-2-0-omni-reasoning-medium', effort: 'medium' }, { id: 'high', model: 'nova-2-0-omni-reasoning-low', effort: 'high' }] },
  'aws:nova-2-0-pro': { default: 'default', options: [{ id: 'default', model: 'nova-2-0-pro' }, { id: 'low', model: 'nova-2-0-pro-reasoning-low', effort: 'low' }, { id: 'medium', model: 'nova-2-0-pro-reasoning-medium', effort: 'medium' }, { id: 'high', model: 'nova-2-0-pro', effort: 'high' }] },
  'azure:claude-4-5-haiku': { default: 'default', options: [{ id: 'default', model: 'claude-4-5-haiku' }, { id: 'low', model: 'claude-4-5-haiku', effort: 'low' }, { id: 'medium', model: 'claude-4-5-haiku', effort: 'medium' }, { id: 'high', model: 'claude-4-5-haiku', effort: 'high' }] },
  'azure:claude-4-5-sonnet': { default: 'default', options: [{ id: 'default', model: 'claude-4-5-sonnet' }, { id: 'low', model: 'claude-4-5-sonnet', effort: 'low' }, { id: 'medium', model: 'claude-4-5-sonnet', effort: 'medium' }, { id: 'high', model: 'claude-4-5-sonnet', effort: 'high' }] },
  'azure:claude-opus-4-5': { default: 'default', options: [{ id: 'default', model: 'claude-opus-4-5' }, { id: 'high', model: 'claude-opus-4-5', effort: 'high' }, { id: 'max', model: 'claude-opus-4-5', effort: 'max' }] },
  'azure:gpt-5-mini': { default: 'default', options: [{ id: 'default', model: 'gpt-5-mini' }, { id: 'minimal', model: 'gpt-5-mini', effort: 'minimal' }, { id: 'low', model: 'gpt-5-mini', effort: 'low' }, { id: 'medium', model: 'gpt-5-mini', effort: 'medium' }, { id: 'high', model: 'gpt-5-mini', effort: 'high' }] },
  'azure:gpt-5-nano': { default: 'default', options: [{ id: 'default', model: 'gpt-5-nano' }, { id: 'minimal', model: 'gpt-5-nano', effort: 'minimal' }, { id: 'low', model: 'gpt-5-nano', effort: 'low' }, { id: 'medium', model: 'gpt-5-nano', effort: 'medium' }, { id: 'high', model: 'gpt-5-nano', effort: 'high' }] },
  'azure:gpt-5-pro': { default: 'default', options: [{ id: 'default', model: 'gpt-5-pro' }, { id: 'minimal', model: 'gpt-5-pro', effort: 'minimal' }, { id: 'low', model: 'gpt-5-pro', effort: 'low' }, { id: 'medium', model: 'gpt-5-pro', effort: 'medium' }, { id: 'high', model: 'gpt-5-pro', effort: 'high' }] },
  'azure:gpt-5.1': { default: 'default', options: [{ id: 'default', model: 'gpt-5.1' }, { id: 'low', model: 'gpt-5.1', effort: 'low' }, { id: 'medium', model: 'gpt-5.1', effort: 'medium' }, { id: 'high', model: 'gpt-5.1', effort: 'high' }] },
  'azure:gpt-5.1-codex': { default: 'default', options: [{ id: 'default', model: 'gpt-5.1-codex' }, { id: 'low', model: 'gpt-5.1-codex', effort: 'low' }, { id: 'medium', model: 'gpt-5.1-codex', effort: 'medium' }, { id: 'high', model: 'gpt-5.1-codex', effort: 'high' }] },
  'azure:gpt-5.2': { default: 'default', options: [{ id: 'default', model: 'gpt-5.2' }, { id: 'low', model: 'gpt-5.2', effort: 'low' }, { id: 'medium', model: 'gpt-5.2', effort: 'medium' }, { id: 'high', model: 'gpt-5.2', effort: 'high' }] },
  'azure:gpt-5.2-codex': { default: 'default', options: [{ id: 'default', model: 'gpt-5.2-codex' }, { id: 'low', model: 'gpt-5.2-codex', effort: 'low' }, { id: 'medium', model: 'gpt-5.2-codex', effort: 'medium' }, { id: 'high', model: 'gpt-5.2-codex', effort: 'high' }] },
  'azure:gpt-oss-120b': { default: 'default', options: [{ id: 'default', model: 'gpt-oss-120b' }, { id: 'low', model: 'gpt-oss-120b', effort: 'low' }, { id: 'medium', model: 'gpt-oss-120b', effort: 'medium' }, { id: 'high', model: 'gpt-oss-120b', effort: 'high' }] },
  'azure:grok-4-fast': { default: 'default', options: [{ id: 'default', model: 'grok-4-fast-non-reasoning' }, { id: 'thinking', model: 'grok-4-fast-reasoning' }] },
  'azure:phi-4': { default: 'default', options: [{ id: 'default', model: 'phi-4' }, { id: 'low', model: 'phi-4', effort: 'low' }, { id: 'medium', model: 'phi-4', effort: 'medium' }, { id: 'high', model: 'phi-4', effort: 'high' }] },
  'azure:phi-4-mini': { default: 'default', options: [{ id: 'default', model: 'phi-4-mini' }, { id: 'low', model: 'phi-4-mini', effort: 'low' }, { id: 'medium', model: 'phi-4-mini', effort: 'medium' }, { id: 'high', model: 'phi-4-mini', effort: 'high' }] },
  'baidu:ernie-5-0': { default: 'default', options: [{ id: 'default', model: 'ernie-5-0-thinking-preview' }, { id: 'low', model: 'ernie-5-0-thinking-preview', effort: 'low' }, { id: 'medium', model: 'ernie-5-0-thinking-preview', effort: 'medium' }, { id: 'high', model: 'ernie-5-0-thinking-preview', effort: 'high' }] },
  'bytedance_seed:doubao-seed-1-8': { default: 'default', options: [{ id: 'default', model: 'doubao-seed-1-8' }, { id: 'low', model: 'doubao-seed-1-8', effort: 'low' }, { id: 'medium', model: 'doubao-seed-1-8', effort: 'medium' }, { id: 'high', model: 'doubao-seed-1-8', effort: 'high' }] },
  'bytedance_seed:doubao-seed-code': { default: 'default', options: [{ id: 'default', model: 'doubao-seed-code' }, { id: 'low', model: 'doubao-seed-code', effort: 'low' }, { id: 'medium', model: 'doubao-seed-code', effort: 'medium' }, { id: 'high', model: 'doubao-seed-code', effort: 'high' }] },
  'bytedance_seed:seed-oss-36b-instruct': { default: 'default', options: [{ id: 'default', model: 'seed-oss-36b-instruct' }, { id: 'low', model: 'seed-oss-36b-instruct', effort: 'low' }, { id: 'medium', model: 'seed-oss-36b-instruct', effort: 'medium' }, { id: 'high', model: 'seed-oss-36b-instruct', effort: 'high' }] },
  'cerebras:gpt-oss-120b': { default: 'default', options: [{ id: 'default', model: 'gpt-oss-120b' }, { id: 'low', model: 'gpt-oss-120b', effort: 'low' }, { id: 'medium', model: 'gpt-oss-120b', effort: 'medium' }, { id: 'high', model: 'gpt-oss-120b', effort: 'high' }] },
  'deepseek:deepseek-v3-2': { default: 'default', options: [{ id: 'default', model: 'deepseek-v3-2' }, { id: 'thinking', model: 'deepseek-v3-2-reasoning' }] },
  'google:gemini-2-5-flash': { default: 'default', options: [{ id: 'default', model: 'gemini-2-5-flash' }, { id: 'high', model: 'gemini-2-5-flash', effort: 'high' }, { id: 'max', model: 'gemini-2-5-flash', effort: 'max' }] },
  'google:gemini-2-5-flash-lite': { default: 'default', options: [{ id: 'default', model: 'gemini-2-5-flash-lite' }, { id: 'high', model: 'gemini-2-5-flash-lite', effort: 'high' }, { id: 'max', model: 'gemini-2-5-flash-lite', effort: 'max' }] },
  'google:gemini-2-5-pro': { default: 'default', options: [{ id: 'default', model: 'gemini-2-5-pro' }, { id: 'high', model: 'gemini-2-5-pro', effort: 'high' }, { id: 'max', model: 'gemini-2-5-pro', effort: 'max' }] },
  'google:gemini-3-1-flash-lite-preview': { default: 'default', options: [{ id: 'default', model: 'gemini-3-1-flash-lite-preview' }, { id: 'low', model: 'gemini-3-1-flash-lite-preview', effort: 'low' }, { id: 'medium', model: 'gemini-3-1-flash-lite-preview', effort: 'medium' }, { id: 'high', model: 'gemini-3-1-flash-lite-preview', effort: 'high' }] },
  'google:gemini-3-1-pro-preview': { default: 'default', options: [{ id: 'default', model: 'gemini-3-1-pro-preview' }, { id: 'low', model: 'gemini-3-1-pro-preview', effort: 'low' }, { id: 'medium', model: 'gemini-3-1-pro-preview', effort: 'medium' }, { id: 'high', model: 'gemini-3-1-pro-preview', effort: 'high' }] },
  'google:gemini-3-flash': { default: 'default', options: [{ id: 'default', model: 'gemini-3-flash' }, { id: 'low', model: 'gemini-3-flash-reasoning', effort: 'low' }, { id: 'high', model: 'gemini-3-flash-reasoning', effort: 'high' }] },
  'google:gemini-3-pro': { default: 'default', options: [{ id: 'default', model: 'gemini-3-pro' }, { id: 'low', model: 'gemini-3-pro', effort: 'low' }, { id: 'high', model: 'gemini-3-pro', effort: 'high' }] },
  'google:gemini-3-pro-low': { default: 'default', options: [{ id: 'default', model: 'gemini-3-pro-low' }, { id: 'low', model: 'gemini-3-pro-low', effort: 'low' }, { id: 'high', model: 'gemini-3-pro-low', effort: 'high' }] },
  'groq:openai/gpt-oss-120b': { default: 'default', options: [{ id: 'default', model: 'openai/gpt-oss-120b' }, { id: 'low', model: 'openai/gpt-oss-120b', effort: 'low' }, { id: 'medium', model: 'openai/gpt-oss-120b', effort: 'medium' }, { id: 'high', model: 'openai/gpt-oss-120b', effort: 'high' }] },
  'groq:openai/gpt-oss-20b': { default: 'default', options: [{ id: 'default', model: 'openai/gpt-oss-20b' }, { id: 'low', model: 'openai/gpt-oss-20b', effort: 'low' }, { id: 'medium', model: 'openai/gpt-oss-20b', effort: 'medium' }, { id: 'high', model: 'openai/gpt-oss-20b', effort: 'high' }] },
  'inception:mercury-2': { default: 'default', options: [{ id: 'default', model: 'mercury-2' }, { id: 'low', model: 'mercury-2', effort: 'low' }, { id: 'medium', model: 'mercury-2', effort: 'medium' }, { id: 'high', model: 'mercury-2', effort: 'high' }] },
  'inclusionai:ling-1t': { default: 'default', options: [{ id: 'default', model: 'ling-1t' }, { id: 'low', model: 'ling-1t', effort: 'low' }, { id: 'medium', model: 'ling-1t', effort: 'medium' }, { id: 'high', model: 'ling-1t', effort: 'high' }] },
  'inclusionai:ling-flash-2-0': { default: 'default', options: [{ id: 'default', model: 'ling-flash-2-0' }, { id: 'low', model: 'ling-flash-2-0', effort: 'low' }, { id: 'medium', model: 'ling-flash-2-0', effort: 'medium' }, { id: 'high', model: 'ling-flash-2-0', effort: 'high' }] },
  'inclusionai:ling-mini-2-0': { default: 'default', options: [{ id: 'default', model: 'ling-mini-2-0' }, { id: 'low', model: 'ling-mini-2-0', effort: 'low' }, { id: 'medium', model: 'ling-mini-2-0', effort: 'medium' }, { id: 'high', model: 'ling-mini-2-0', effort: 'high' }] },
  'inclusionai:ring-flash-2-0': { default: 'default', options: [{ id: 'default', model: 'ring-flash-2-0' }, { id: 'low', model: 'ring-flash-2-0', effort: 'low' }, { id: 'medium', model: 'ring-flash-2-0', effort: 'medium' }, { id: 'high', model: 'ring-flash-2-0', effort: 'high' }] },
  'kimi:kimi-k2-5': { default: 'default', options: [{ id: 'default', model: 'kimi-k2-5-non-reasoning' }, { id: 'thinking', model: 'kimi-k2-5' }] },
  'korea-telecom:mi-dm-k-2-5-pro-dec28': { default: 'default', options: [{ id: 'default', model: 'mi-dm-k-2-5-pro-dec28' }, { id: 'low', model: 'mi-dm-k-2-5-pro-dec28', effort: 'low' }, { id: 'medium', model: 'mi-dm-k-2-5-pro-dec28', effort: 'medium' }, { id: 'high', model: 'mi-dm-k-2-5-pro-dec28', effort: 'high' }] },
  'lg:k-exaone': { default: 'default', options: [{ id: 'default', model: 'k-exaone-non-reasoning' }, { id: 'low', model: 'k-exaone', effort: 'low' }, { id: 'medium', model: 'k-exaone', effort: 'medium' }, { id: 'high', model: 'k-exaone', effort: 'high' }] },
  'liquidai:lfm2-5-1-2b': { default: 'default', options: [{ id: 'default', model: 'lfm2-5-1-2b-thinking' }, { id: 'low', model: 'lfm2-5-1-2b-thinking', effort: 'low' }, { id: 'medium', model: 'lfm2-5-1-2b-thinking', effort: 'medium' }, { id: 'high', model: 'lfm2-5-1-2b-thinking', effort: 'high' }] },
  'mbzuai:k2-think-v2': { default: 'default', options: [{ id: 'default', model: 'k2-think-v2' }, { id: 'low', model: 'k2-think-v2', effort: 'low' }, { id: 'medium', model: 'k2-think-v2', effort: 'medium' }, { id: 'high', model: 'k2-think-v2', effort: 'high' }] },
  'mbzuai:k2-v2': { default: 'default', options: [{ id: 'default', model: 'k2-v2' }, { id: 'low', model: 'k2-v2', effort: 'low' }, { id: 'medium', model: 'k2-v2', effort: 'medium' }, { id: 'high', model: 'k2-v2', effort: 'high' }] },
  'mbzuai:k2-v2-low': { default: 'default', options: [{ id: 'default', model: 'k2-v2-low' }, { id: 'low', model: 'k2-v2-low', effort: 'low' }, { id: 'medium', model: 'k2-v2-low', effort: 'medium' }, { id: 'high', model: 'k2-v2-low', effort: 'high' }] },
  'mbzuai:k2-v2-medium': { default: 'default', options: [{ id: 'default', model: 'k2-v2-medium' }, { id: 'low', model: 'k2-v2-medium', effort: 'low' }, { id: 'medium', model: 'k2-v2-medium', effort: 'medium' }, { id: 'high', model: 'k2-v2-medium', effort: 'high' }] },
  'meta:llama-4-maverick': { default: 'default', options: [{ id: 'default', model: 'llama-4-maverick' }, { id: 'low', model: 'llama-4-maverick', effort: 'low' }, { id: 'medium', model: 'llama-4-maverick', effort: 'medium' }, { id: 'high', model: 'llama-4-maverick', effort: 'high' }] },
  'meta:llama-4-scout': { default: 'default', options: [{ id: 'default', model: 'llama-4-scout' }, { id: 'low', model: 'llama-4-scout', effort: 'low' }, { id: 'medium', model: 'llama-4-scout', effort: 'medium' }, { id: 'high', model: 'llama-4-scout', effort: 'high' }] },
  'motif-technologies:motif-2-12-7b': { default: 'default', options: [{ id: 'default', model: 'motif-2-12-7b' }, { id: 'low', model: 'motif-2-12-7b', effort: 'low' }, { id: 'medium', model: 'motif-2-12-7b', effort: 'medium' }, { id: 'high', model: 'motif-2-12-7b', effort: 'high' }] },
  'naver:hyperclova-x-seed-think-32b': { default: 'default', options: [{ id: 'default', model: 'hyperclova-x-seed-think-32b' }, { id: 'low', model: 'hyperclova-x-seed-think-32b', effort: 'low' }, { id: 'medium', model: 'hyperclova-x-seed-think-32b', effort: 'medium' }, { id: 'high', model: 'hyperclova-x-seed-think-32b', effort: 'high' }] },
  'nous-research:deephermes-3-llama-3-1-8b-preview': { default: 'default', options: [{ id: 'default', model: 'deephermes-3-llama-3-1-8b-preview' }, { id: 'low', model: 'deephermes-3-llama-3-1-8b-preview', effort: 'low' }, { id: 'medium', model: 'deephermes-3-llama-3-1-8b-preview', effort: 'medium' }, { id: 'high', model: 'deephermes-3-llama-3-1-8b-preview', effort: 'high' }] },
  'nous-research:hermes-4-405b': { default: 'default', options: [{ id: 'default', model: 'hermes-4-405b' }, { id: 'low', model: 'hermes-4-405b', effort: 'low' }, { id: 'medium', model: 'hermes-4-405b', effort: 'medium' }, { id: 'high', model: 'hermes-4-405b', effort: 'high' }] },
  'nous-research:hermes-4-70b': { default: 'default', options: [{ id: 'default', model: 'hermes-4-70b' }, { id: 'low', model: 'hermes-4-70b', effort: 'low' }, { id: 'medium', model: 'hermes-4-70b', effort: 'medium' }, { id: 'high', model: 'hermes-4-70b', effort: 'high' }] },
  'nvidia:llama-3-1-nemotron-nano-4b-v1-1': { default: 'default', options: [{ id: 'default', model: 'llama-3-1-nemotron-nano-4b-v1-1' }, { id: 'low', model: 'llama-3-1-nemotron-nano-4b-v1-1', effort: 'low' }, { id: 'medium', model: 'llama-3-1-nemotron-nano-4b-v1-1', effort: 'medium' }, { id: 'high', model: 'llama-3-1-nemotron-nano-4b-v1-1', effort: 'high' }] },
  'nvidia:llama-3-3-nemotron-super-49b': { default: 'default', options: [{ id: 'default', model: 'llama-3-3-nemotron-super-49b' }, { id: 'low', model: 'llama-3-3-nemotron-super-49b', effort: 'low' }, { id: 'medium', model: 'llama-3-3-nemotron-super-49b', effort: 'medium' }, { id: 'high', model: 'llama-3-3-nemotron-super-49b', effort: 'high' }] },
  'nvidia:llama-nemotron-super-49b-v1-5': { default: 'default', options: [{ id: 'default', model: 'llama-nemotron-super-49b-v1-5' }, { id: 'low', model: 'llama-nemotron-super-49b-v1-5', effort: 'low' }, { id: 'medium', model: 'llama-nemotron-super-49b-v1-5', effort: 'medium' }, { id: 'high', model: 'llama-nemotron-super-49b-v1-5', effort: 'high' }] },
  'nvidia:llama-nemotron-ultra': { default: 'default', options: [{ id: 'default', model: 'llama-nemotron-ultra' }, { id: 'low', model: 'llama-nemotron-ultra', effort: 'low' }, { id: 'medium', model: 'llama-nemotron-ultra', effort: 'medium' }, { id: 'high', model: 'llama-nemotron-ultra', effort: 'high' }] },
  'nvidia:nvidia-nemotron-3-nano-30b-a3b': { default: 'default', options: [{ id: 'default', model: 'nvidia-nemotron-3-nano-30b-a3b' }, { id: 'low', model: 'nvidia-nemotron-3-nano-30b-a3b-reasoning', effort: 'low' }, { id: 'medium', model: 'nvidia-nemotron-3-nano-30b-a3b-reasoning', effort: 'medium' }, { id: 'high', model: 'nvidia-nemotron-3-nano-30b-a3b-reasoning', effort: 'high' }] },
  'nvidia:nvidia-nemotron-nano-12b-v2-vl': { default: 'default', options: [{ id: 'default', model: 'nvidia-nemotron-nano-12b-v2-vl' }, { id: 'low', model: 'nvidia-nemotron-nano-12b-v2-vl-reasoning', effort: 'low' }, { id: 'medium', model: 'nvidia-nemotron-nano-12b-v2-vl-reasoning', effort: 'medium' }, { id: 'high', model: 'nvidia-nemotron-nano-12b-v2-vl-reasoning', effort: 'high' }] },
  'nvidia:nvidia-nemotron-nano-9b-v2': { default: 'default', options: [{ id: 'default', model: 'nvidia-nemotron-nano-9b-v2' }, { id: 'low', model: 'nvidia-nemotron-nano-9b-v2', effort: 'low' }, { id: 'medium', model: 'nvidia-nemotron-nano-9b-v2', effort: 'medium' }, { id: 'high', model: 'nvidia-nemotron-nano-9b-v2', effort: 'high' }] },
  'openai:gpt-5-1-codex-mini': { default: 'default', options: [{ id: 'default', model: 'gpt-5-1-codex-mini' }, { id: 'low', model: 'gpt-5-1-codex-mini', effort: 'low' }, { id: 'medium', model: 'gpt-5-1-codex-mini', effort: 'medium' }, { id: 'high', model: 'gpt-5-1-codex-mini', effort: 'high' }] },
  'openai:gpt-5-2': { default: 'default', options: [{ id: 'default', model: 'gpt-5-2-non-reasoning' }, { id: 'low', model: 'gpt-5-2', effort: 'low' }, { id: 'medium', model: 'gpt-5-2', effort: 'medium' }, { id: 'high', model: 'gpt-5-2', effort: 'high' }, { id: 'xhigh', model: 'gpt-5-2', effort: 'xhigh' }] },
  'openai:gpt-5-2-codex': { default: 'default', options: [{ id: 'default', model: 'gpt-5-2-codex' }, { id: 'low', model: 'gpt-5-2-codex', effort: 'low' }, { id: 'medium', model: 'gpt-5-2-codex', effort: 'medium' }, { id: 'high', model: 'gpt-5-2-codex', effort: 'high' }, { id: 'xhigh', model: 'gpt-5-2-codex', effort: 'xhigh' }] },
  'openai:gpt-5-2-medium': { default: 'default', options: [{ id: 'default', model: 'gpt-5-2-medium' }, { id: 'minimal', model: 'gpt-5-2-medium', effort: 'minimal' }, { id: 'low', model: 'gpt-5-2-medium', effort: 'low' }, { id: 'medium', model: 'gpt-5-2-medium', effort: 'medium' }, { id: 'high', model: 'gpt-5-2-medium', effort: 'high' }] },
  'openai:gpt-5-3-codex': { default: 'default', options: [{ id: 'default', model: 'gpt-5-3-codex' }, { id: 'low', model: 'gpt-5-3-codex', effort: 'low' }, { id: 'medium', model: 'gpt-5-3-codex', effort: 'medium' }, { id: 'high', model: 'gpt-5-3-codex', effort: 'high' }, { id: 'xhigh', model: 'gpt-5-3-codex', effort: 'xhigh' }] },
  'openai:gpt-5-mini': { default: 'default', options: [{ id: 'default', model: 'gpt-5-mini' }, { id: 'minimal', model: 'gpt-5-mini', effort: 'minimal' }, { id: 'low', model: 'gpt-5-mini', effort: 'low' }, { id: 'medium', model: 'gpt-5-mini', effort: 'medium' }, { id: 'high', model: 'gpt-5-mini', effort: 'high' }] },
  'openai:gpt-5-mini-medium': { default: 'default', options: [{ id: 'default', model: 'gpt-5-mini-medium' }, { id: 'minimal', model: 'gpt-5-mini-medium', effort: 'minimal' }, { id: 'low', model: 'gpt-5-mini-medium', effort: 'low' }, { id: 'medium', model: 'gpt-5-mini-medium', effort: 'medium' }, { id: 'high', model: 'gpt-5-mini-medium', effort: 'high' }] },
  'openai:gpt-5-mini-minimal': { default: 'default', options: [{ id: 'default', model: 'gpt-5-mini-minimal' }, { id: 'minimal', model: 'gpt-5-mini-minimal', effort: 'minimal' }, { id: 'low', model: 'gpt-5-mini-minimal', effort: 'low' }, { id: 'medium', model: 'gpt-5-mini-minimal', effort: 'medium' }, { id: 'high', model: 'gpt-5-mini-minimal', effort: 'high' }] },
  'openai:gpt-5-minimal': { default: 'default', options: [{ id: 'default', model: 'gpt-5-minimal' }, { id: 'minimal', model: 'gpt-5-minimal', effort: 'minimal' }, { id: 'low', model: 'gpt-5-minimal', effort: 'low' }, { id: 'medium', model: 'gpt-5-minimal', effort: 'medium' }, { id: 'high', model: 'gpt-5-minimal', effort: 'high' }] },
  'openai:gpt-5-nano': { default: 'default', options: [{ id: 'default', model: 'gpt-5-nano' }, { id: 'minimal', model: 'gpt-5-nano', effort: 'minimal' }, { id: 'low', model: 'gpt-5-nano', effort: 'low' }, { id: 'medium', model: 'gpt-5-nano', effort: 'medium' }, { id: 'high', model: 'gpt-5-nano', effort: 'high' }] },
  'openai:gpt-5-nano-medium': { default: 'default', options: [{ id: 'default', model: 'gpt-5-nano-medium' }, { id: 'minimal', model: 'gpt-5-nano-medium', effort: 'minimal' }, { id: 'low', model: 'gpt-5-nano-medium', effort: 'low' }, { id: 'medium', model: 'gpt-5-nano-medium', effort: 'medium' }, { id: 'high', model: 'gpt-5-nano-medium', effort: 'high' }] },
  'openai:gpt-5-nano-minimal': { default: 'default', options: [{ id: 'default', model: 'gpt-5-nano-minimal' }, { id: 'minimal', model: 'gpt-5-nano-minimal', effort: 'minimal' }, { id: 'low', model: 'gpt-5-nano-minimal', effort: 'low' }, { id: 'medium', model: 'gpt-5-nano-minimal', effort: 'medium' }, { id: 'high', model: 'gpt-5-nano-minimal', effort: 'high' }] },
  'openai:gpt-oss-120b': { default: 'default', options: [{ id: 'default', model: 'gpt-oss-120b' }, { id: 'low', model: 'gpt-oss-120b', effort: 'low' }, { id: 'medium', model: 'gpt-oss-120b', effort: 'medium' }, { id: 'high', model: 'gpt-oss-120b', effort: 'high' }] },
  'openai:gpt-oss-120b-low': { default: 'default', options: [{ id: 'default', model: 'gpt-oss-120b-low' }, { id: 'low', model: 'gpt-oss-120b-low', effort: 'low' }, { id: 'medium', model: 'gpt-oss-120b-low', effort: 'medium' }, { id: 'high', model: 'gpt-oss-120b-low', effort: 'high' }] },
  'openai:gpt-oss-20b': { default: 'default', options: [{ id: 'default', model: 'gpt-oss-20b' }, { id: 'low', model: 'gpt-oss-20b', effort: 'low' }, { id: 'medium', model: 'gpt-oss-20b', effort: 'medium' }, { id: 'high', model: 'gpt-oss-20b', effort: 'high' }] },
  'openai:gpt-oss-20b-low': { default: 'default', options: [{ id: 'default', model: 'gpt-oss-20b-low' }, { id: 'low', model: 'gpt-oss-20b-low', effort: 'low' }, { id: 'medium', model: 'gpt-oss-20b-low', effort: 'medium' }, { id: 'high', model: 'gpt-oss-20b-low', effort: 'high' }] },
  'prime-intellect:intellect-3': { default: 'default', options: [{ id: 'default', model: 'intellect-3' }, { id: 'low', model: 'intellect-3', effort: 'low' }, { id: 'medium', model: 'intellect-3', effort: 'medium' }, { id: 'high', model: 'intellect-3', effort: 'high' }] },
  'reka-ai:reka-flash-3': { default: 'default', options: [{ id: 'default', model: 'reka-flash-3' }, { id: 'low', model: 'reka-flash-3', effort: 'low' }, { id: 'medium', model: 'reka-flash-3', effort: 'medium' }, { id: 'high', model: 'reka-flash-3', effort: 'high' }] },
  'servicenow:apriel-v1-6-15b-thinker': { default: 'default', options: [{ id: 'default', model: 'apriel-v1-6-15b-thinker' }, { id: 'low', model: 'apriel-v1-6-15b-thinker', effort: 'low' }, { id: 'medium', model: 'apriel-v1-6-15b-thinker', effort: 'medium' }, { id: 'high', model: 'apriel-v1-6-15b-thinker', effort: 'high' }] },
  'stepfun:step3-vl-10b': { default: 'default', options: [{ id: 'default', model: 'step3-vl-10b' }, { id: 'low', model: 'step3-vl-10b', effort: 'low' }, { id: 'medium', model: 'step3-vl-10b', effort: 'medium' }, { id: 'high', model: 'step3-vl-10b', effort: 'high' }] },
  'tii-uae:falcon-h1r-7b': { default: 'default', options: [{ id: 'default', model: 'falcon-h1r-7b' }, { id: 'low', model: 'falcon-h1r-7b', effort: 'low' }, { id: 'medium', model: 'falcon-h1r-7b', effort: 'medium' }, { id: 'high', model: 'falcon-h1r-7b', effort: 'high' }] },
  'trillionlabs:tri-21b-think-preview': { default: 'default', options: [{ id: 'default', model: 'tri-21b-think-preview' }, { id: 'low', model: 'tri-21b-think-preview', effort: 'low' }, { id: 'medium', model: 'tri-21b-think-preview', effort: 'medium' }, { id: 'high', model: 'tri-21b-think-preview', effort: 'high' }] },
  'trillionlabs:tri-21b-think-v0-5': { default: 'default', options: [{ id: 'default', model: 'tri-21b-think-v0-5' }, { id: 'low', model: 'tri-21b-think-v0-5', effort: 'low' }, { id: 'medium', model: 'tri-21b-think-v0-5', effort: 'medium' }, { id: 'high', model: 'tri-21b-think-v0-5', effort: 'high' }] },
  'upstage:solar-open-100b': { default: 'default', options: [{ id: 'default', model: 'solar-open-100b-reasoning' }, { id: 'low', model: 'solar-open-100b-reasoning', effort: 'low' }, { id: 'medium', model: 'solar-open-100b-reasoning', effort: 'medium' }, { id: 'high', model: 'solar-open-100b-reasoning', effort: 'high' }] },
  'upstage:solar-pro-2': { default: 'default', options: [{ id: 'default', model: 'solar-pro-2' }, { id: 'low', model: 'solar-pro-2', effort: 'low' }, { id: 'medium', model: 'solar-pro-2', effort: 'medium' }, { id: 'high', model: 'solar-pro-2', effort: 'high' }] },
  'xai:grok-4-1-fast': { default: 'default', options: [{ id: 'default', model: 'grok-4-1-fast' }, { id: 'thinking', model: 'grok-4-1-fast-reasoning' }] },
  'xai:grok-4-fast': { default: 'default', options: [{ id: 'default', model: 'grok-4-fast' }, { id: 'thinking', model: 'grok-4-fast-reasoning' }] },
  'xiaomi:mimo-v2-0206': { default: 'default', options: [{ id: 'default', model: 'mimo-v2-0206' }, { id: 'low', model: 'mimo-v2-0206', effort: 'low' }, { id: 'medium', model: 'mimo-v2-0206', effort: 'medium' }, { id: 'high', model: 'mimo-v2-0206', effort: 'high' }] },
  'xiaomi:mimo-v2-flash': { default: 'default', options: [{ id: 'default', model: 'mimo-v2-flash' }, { id: 'low', model: 'mimo-v2-flash-reasoning', effort: 'low' }, { id: 'medium', model: 'mimo-v2-flash-reasoning', effort: 'medium' }, { id: 'high', model: 'mimo-v2-flash-reasoning', effort: 'high' }] },
  'zai:glm-4-6v': { default: 'default', options: [{ id: 'default', model: 'glm-4-6v' }, { id: 'thinking', model: 'glm-4-6v-reasoning' }] },
  'zai:glm-4-7': { default: 'default', options: [{ id: 'default', model: 'glm-4-7-non-reasoning' }, { id: 'thinking', model: 'glm-4-7' }] },
  'zai:glm-4-7-flash': { default: 'default', options: [{ id: 'default', model: 'glm-4-7-flash-non-reasoning' }, { id: 'thinking', model: 'glm-4-7-flash' }] },
  'zai:glm-5': { default: 'default', options: [{ id: 'default', model: 'glm-5-non-reasoning' }, { id: 'thinking', model: 'glm-5' }] },
}

const MODEL_TO_REASONING_GROUP: Record<string, string> = {
  'ai2:olmo-3-1-32b-think': 'ai2:olmo-3-1-32b-think',
  'ai2:olmo-3-7b-think': 'ai2:olmo-3-7b-think',
  'ai21-labs:jamba-reasoning-3b': 'ai21-labs:jamba-reasoning-3b',
  'alibaba:qwen3-235b-2507': 'alibaba:qwen3-235b-2507',
  'alibaba:qwen3-235b-a22b-2507': 'alibaba:qwen3-235b-a22b-2507',
  'alibaba:qwen3-30b-a3b-2507': 'alibaba:qwen3-30b-a3b-2507',
  'alibaba:qwen3-5-122b-a10b': 'alibaba:qwen3-5-122b-a10b',
  'alibaba:qwen3-5-122b-a10b-non-reasoning': 'alibaba:qwen3-5-122b-a10b',
  'alibaba:qwen3-5-27b': 'alibaba:qwen3-5-27b',
  'alibaba:qwen3-5-27b-non-reasoning': 'alibaba:qwen3-5-27b',
  'alibaba:qwen3-5-35b-a3b': 'alibaba:qwen3-5-35b-a3b',
  'alibaba:qwen3-5-35b-a3b-non-reasoning': 'alibaba:qwen3-5-35b-a3b',
  'alibaba:qwen3-5-397b-a17b': 'alibaba:qwen3-5-397b-a17b',
  'alibaba:qwen3-5-397b-a17b-non-reasoning': 'alibaba:qwen3-5-397b-a17b',
  'alibaba:qwen3-max': 'alibaba:qwen3-max',
  'alibaba:qwen3-max-thinking-preview': 'alibaba:qwen3-max',
  'alibaba:qwen3-next-80b-a3b-reasoning': 'alibaba:qwen3-next-80b-a3b',
  'alibaba:qwen3-omni-30b-a3b-reasoning': 'alibaba:qwen3-omni-30b-a3b',
  'alibaba:qwen3-vl-235b-a22b-reasoning': 'alibaba:qwen3-vl-235b-a22b',
  'alibaba:qwen3-vl-30b-a3b-reasoning': 'alibaba:qwen3-vl-30b-a3b',
  'alibaba:qwen3-vl-32b-reasoning': 'alibaba:qwen3-vl-32b',
  'alibaba:qwen3-vl-4b-reasoning': 'alibaba:qwen3-vl-4b',
  'alibaba:qwen3-vl-8b-reasoning': 'alibaba:qwen3-vl-8b',
  'anthropic:claude-4-5-haiku': 'anthropic:claude-4-5-haiku',
  'anthropic:claude-4-5-haiku-reasoning': 'anthropic:claude-4-5-haiku',
  'anthropic:claude-4-5-sonnet': 'anthropic:claude-4-5-sonnet',
  'anthropic:claude-4-5-sonnet-thinking': 'anthropic:claude-4-5-sonnet',
  'anthropic:claude-opus-4-5': 'anthropic:claude-opus-4-5',
  'anthropic:claude-opus-4-5-thinking': 'anthropic:claude-opus-4-5',
  'anthropic:claude-opus-4-6': 'anthropic:claude-opus-4-6',
  'anthropic:claude-opus-4-6-adaptive': 'anthropic:claude-opus-4-6',
  'anthropic:claude-sonnet-4-6': 'anthropic:claude-sonnet-4-6',
  'anthropic:claude-sonnet-4-6-adaptive': 'anthropic:claude-sonnet-4-6',
  'anthropic:claude-sonnet-4-6-non-reasoning-low-effort': 'anthropic:claude-sonnet-4-6',
  'aws:nova-2-0-lite': 'aws:nova-2-0-lite',
  'aws:nova-2-0-lite-reasoning-low': 'aws:nova-2-0-lite',
  'aws:nova-2-0-lite-reasoning-medium': 'aws:nova-2-0-lite',
  'aws:nova-2-0-omni': 'aws:nova-2-0-omni',
  'aws:nova-2-0-omni-reasoning-low': 'aws:nova-2-0-omni',
  'aws:nova-2-0-omni-reasoning-medium': 'aws:nova-2-0-omni',
  'aws:nova-2-0-pro': 'aws:nova-2-0-pro',
  'aws:nova-2-0-pro-reasoning-low': 'aws:nova-2-0-pro',
  'aws:nova-2-0-pro-reasoning-medium': 'aws:nova-2-0-pro',
  'azure:claude-4-5-haiku': 'azure:claude-4-5-haiku',
  'azure:claude-4-5-sonnet': 'azure:claude-4-5-sonnet',
  'azure:claude-opus-4-5': 'azure:claude-opus-4-5',
  'azure:gpt-5-mini': 'azure:gpt-5-mini',
  'azure:gpt-5-nano': 'azure:gpt-5-nano',
  'azure:gpt-5-pro': 'azure:gpt-5-pro',
  'azure:gpt-5.1': 'azure:gpt-5.1',
  'azure:gpt-5.1-codex': 'azure:gpt-5.1-codex',
  'azure:gpt-5.2': 'azure:gpt-5.2',
  'azure:gpt-5.2-codex': 'azure:gpt-5.2-codex',
  'azure:gpt-oss-120b': 'azure:gpt-oss-120b',
  'azure:grok-4-fast-non-reasoning': 'azure:grok-4-fast',
  'azure:grok-4-fast-reasoning': 'azure:grok-4-fast',
  'azure:phi-4': 'azure:phi-4',
  'azure:phi-4-mini': 'azure:phi-4-mini',
  'baidu:ernie-5-0-thinking-preview': 'baidu:ernie-5-0',
  'bytedance_seed:doubao-seed-1-8': 'bytedance_seed:doubao-seed-1-8',
  'bytedance_seed:doubao-seed-code': 'bytedance_seed:doubao-seed-code',
  'bytedance_seed:seed-oss-36b-instruct': 'bytedance_seed:seed-oss-36b-instruct',
  'cerebras:gpt-oss-120b': 'cerebras:gpt-oss-120b',
  'deepseek:deepseek-v3-2': 'deepseek:deepseek-v3-2',
  'deepseek:deepseek-v3-2-reasoning': 'deepseek:deepseek-v3-2',
  'google:gemini-2-5-flash': 'google:gemini-2-5-flash',
  'google:gemini-2-5-flash-lite': 'google:gemini-2-5-flash-lite',
  'google:gemini-2-5-pro': 'google:gemini-2-5-pro',
  'google:gemini-3-1-flash-lite-preview': 'google:gemini-3-1-flash-lite-preview',
  'google:gemini-3-1-pro-preview': 'google:gemini-3-1-pro-preview',
  'google:gemini-3-flash': 'google:gemini-3-flash',
  'google:gemini-3-flash-reasoning': 'google:gemini-3-flash',
  'google:gemini-3-pro': 'google:gemini-3-pro',
  'google:gemini-3-pro-low': 'google:gemini-3-pro-low',
  'groq:openai/gpt-oss-120b': 'groq:openai/gpt-oss-120b',
  'groq:openai/gpt-oss-20b': 'groq:openai/gpt-oss-20b',
  'inception:mercury-2': 'inception:mercury-2',
  'inclusionai:ling-1t': 'inclusionai:ling-1t',
  'inclusionai:ling-flash-2-0': 'inclusionai:ling-flash-2-0',
  'inclusionai:ling-mini-2-0': 'inclusionai:ling-mini-2-0',
  'inclusionai:ring-flash-2-0': 'inclusionai:ring-flash-2-0',
  'kimi:kimi-k2-5': 'kimi:kimi-k2-5',
  'kimi:kimi-k2-5-non-reasoning': 'kimi:kimi-k2-5',
  'korea-telecom:mi-dm-k-2-5-pro-dec28': 'korea-telecom:mi-dm-k-2-5-pro-dec28',
  'lg:k-exaone': 'lg:k-exaone',
  'lg:k-exaone-non-reasoning': 'lg:k-exaone',
  'liquidai:lfm2-5-1-2b-thinking': 'liquidai:lfm2-5-1-2b',
  'mbzuai:k2-think-v2': 'mbzuai:k2-think-v2',
  'mbzuai:k2-v2': 'mbzuai:k2-v2',
  'mbzuai:k2-v2-low': 'mbzuai:k2-v2-low',
  'mbzuai:k2-v2-medium': 'mbzuai:k2-v2-medium',
  'meta:llama-4-maverick': 'meta:llama-4-maverick',
  'meta:llama-4-scout': 'meta:llama-4-scout',
  'motif-technologies:motif-2-12-7b': 'motif-technologies:motif-2-12-7b',
  'naver:hyperclova-x-seed-think-32b': 'naver:hyperclova-x-seed-think-32b',
  'nous-research:deephermes-3-llama-3-1-8b-preview': 'nous-research:deephermes-3-llama-3-1-8b-preview',
  'nous-research:hermes-4-405b': 'nous-research:hermes-4-405b',
  'nous-research:hermes-4-70b': 'nous-research:hermes-4-70b',
  'nvidia:llama-3-1-nemotron-nano-4b-v1-1': 'nvidia:llama-3-1-nemotron-nano-4b-v1-1',
  'nvidia:llama-3-3-nemotron-super-49b': 'nvidia:llama-3-3-nemotron-super-49b',
  'nvidia:llama-nemotron-super-49b-v1-5': 'nvidia:llama-nemotron-super-49b-v1-5',
  'nvidia:llama-nemotron-ultra': 'nvidia:llama-nemotron-ultra',
  'nvidia:nvidia-nemotron-3-nano-30b-a3b': 'nvidia:nvidia-nemotron-3-nano-30b-a3b',
  'nvidia:nvidia-nemotron-3-nano-30b-a3b-reasoning': 'nvidia:nvidia-nemotron-3-nano-30b-a3b',
  'nvidia:nvidia-nemotron-nano-12b-v2-vl': 'nvidia:nvidia-nemotron-nano-12b-v2-vl',
  'nvidia:nvidia-nemotron-nano-12b-v2-vl-reasoning': 'nvidia:nvidia-nemotron-nano-12b-v2-vl',
  'nvidia:nvidia-nemotron-nano-9b-v2': 'nvidia:nvidia-nemotron-nano-9b-v2',
  'openai:gpt-5-1-codex-mini': 'openai:gpt-5-1-codex-mini',
  'openai:gpt-5-2': 'openai:gpt-5-2',
  'openai:gpt-5-2-codex': 'openai:gpt-5-2-codex',
  'openai:gpt-5-2-medium': 'openai:gpt-5-2-medium',
  'openai:gpt-5-2-non-reasoning': 'openai:gpt-5-2',
  'openai:gpt-5-3-codex': 'openai:gpt-5-3-codex',
  'openai:gpt-5-mini': 'openai:gpt-5-mini',
  'openai:gpt-5-mini-medium': 'openai:gpt-5-mini-medium',
  'openai:gpt-5-mini-minimal': 'openai:gpt-5-mini-minimal',
  'openai:gpt-5-minimal': 'openai:gpt-5-minimal',
  'openai:gpt-5-nano': 'openai:gpt-5-nano',
  'openai:gpt-5-nano-medium': 'openai:gpt-5-nano-medium',
  'openai:gpt-5-nano-minimal': 'openai:gpt-5-nano-minimal',
  'openai:gpt-oss-120b': 'openai:gpt-oss-120b',
  'openai:gpt-oss-120b-low': 'openai:gpt-oss-120b-low',
  'openai:gpt-oss-20b': 'openai:gpt-oss-20b',
  'openai:gpt-oss-20b-low': 'openai:gpt-oss-20b-low',
  'prime-intellect:intellect-3': 'prime-intellect:intellect-3',
  'reka-ai:reka-flash-3': 'reka-ai:reka-flash-3',
  'servicenow:apriel-v1-6-15b-thinker': 'servicenow:apriel-v1-6-15b-thinker',
  'stepfun:step3-vl-10b': 'stepfun:step3-vl-10b',
  'tii-uae:falcon-h1r-7b': 'tii-uae:falcon-h1r-7b',
  'trillionlabs:tri-21b-think-preview': 'trillionlabs:tri-21b-think-preview',
  'trillionlabs:tri-21b-think-v0-5': 'trillionlabs:tri-21b-think-v0-5',
  'upstage:solar-open-100b-reasoning': 'upstage:solar-open-100b',
  'upstage:solar-pro-2': 'upstage:solar-pro-2',
  'xai:grok-4-1-fast': 'xai:grok-4-1-fast',
  'xai:grok-4-1-fast-reasoning': 'xai:grok-4-1-fast',
  'xai:grok-4-fast': 'xai:grok-4-fast',
  'xai:grok-4-fast-reasoning': 'xai:grok-4-fast',
  'xiaomi:mimo-v2-0206': 'xiaomi:mimo-v2-0206',
  'xiaomi:mimo-v2-flash': 'xiaomi:mimo-v2-flash',
  'xiaomi:mimo-v2-flash-reasoning': 'xiaomi:mimo-v2-flash',
  'zai:glm-4-6v': 'zai:glm-4-6v',
  'zai:glm-4-6v-reasoning': 'zai:glm-4-6v',
  'zai:glm-4-7': 'zai:glm-4-7',
  'zai:glm-4-7-flash': 'zai:glm-4-7-flash',
  'zai:glm-4-7-flash-non-reasoning': 'zai:glm-4-7-flash',
  'zai:glm-4-7-non-reasoning': 'zai:glm-4-7',
  'zai:glm-5': 'zai:glm-5',
  'zai:glm-5-non-reasoning': 'zai:glm-5',
}

function keyOf(provider: string, model: string): string {
  return `${provider.toLowerCase()}:${model.toLowerCase()}`
}

function buildControl(spec: ReasoningGroupSpec): ReasoningControl {
  return {
    default: spec.default,
    options: spec.options.map(option => ({ ...option })),
  }
}

export function getModelReasoningControl(provider: string, model: string): ReasoningControl | undefined {
  const modelKey = keyOf(provider, model)
  const groupKey = MODEL_TO_REASONING_GROUP[modelKey]
  if (!groupKey)
    return undefined

  const spec = REASONING_GROUP_SPECS[groupKey]
  if (!spec)
    return undefined

  return buildControl(spec)
}
